version: "3.7"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      SQL_MODE: ""
    
  mongo:
    image: mongo
    ports:
      - 27017:27017

networks:
  spear:
    external: true
